-- MathComplete Lab auth + progress schema
-- Run this in Supabase SQL Editor after enabling Email auth.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text default '',
  plan text not null default 'free',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  game_id text not null,
  course text default '',
  topic text default '',
  difficulty text default '',
  question_key text not null,
  question_latex text default '',
  question_text text default '',
  correct_answer_latex text default '',
  selected_answer_latex text default '',
  is_correct boolean not null default false,
  time_spent_seconds integer,
  created_at timestamptz not null default now()
);

create table if not exists public.mistakes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  game_id text not null,
  course text default '',
  topic text default '',
  difficulty text default '',
  question_key text not null,
  question_latex text default '',
  question_text text default '',
  correct_answer_latex text default '',
  last_selected_answer_latex text default '',
  mistake_count integer not null default 1,
  review_success_count integer not null default 0,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, game_id, question_key)
);

create table if not exists public.favorite_tools (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  game_id text not null,
  created_at timestamptz not null default now(),
  unique (user_id, game_id)
);

create index if not exists attempts_user_created_idx
  on public.attempts (user_id, created_at desc);

create index if not exists mistakes_user_status_updated_idx
  on public.mistakes (user_id, status, updated_at desc);

create index if not exists favorite_tools_user_created_idx
  on public.favorite_tools (user_id, created_at desc);

alter table public.profiles enable row level security;
alter table public.attempts enable row level security;
alter table public.mistakes enable row level security;
alter table public.favorite_tools enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
  on public.profiles for select
  using (auth.uid() = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
  on public.profiles for insert
  with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

drop policy if exists "attempts_select_own" on public.attempts;
create policy "attempts_select_own"
  on public.attempts for select
  using (auth.uid() = user_id);

drop policy if exists "attempts_insert_own" on public.attempts;
create policy "attempts_insert_own"
  on public.attempts for insert
  with check (auth.uid() = user_id);

drop policy if exists "mistakes_select_own" on public.mistakes;
create policy "mistakes_select_own"
  on public.mistakes for select
  using (auth.uid() = user_id);

drop policy if exists "mistakes_insert_own" on public.mistakes;
create policy "mistakes_insert_own"
  on public.mistakes for insert
  with check (auth.uid() = user_id);

drop policy if exists "mistakes_update_own" on public.mistakes;
create policy "mistakes_update_own"
  on public.mistakes for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "favorite_tools_select_own" on public.favorite_tools;
create policy "favorite_tools_select_own"
  on public.favorite_tools for select
  using (auth.uid() = user_id);

drop policy if exists "favorite_tools_insert_own" on public.favorite_tools;
create policy "favorite_tools_insert_own"
  on public.favorite_tools for insert
  with check (auth.uid() = user_id);

drop policy if exists "favorite_tools_delete_own" on public.favorite_tools;
create policy "favorite_tools_delete_own"
  on public.favorite_tools for delete
  using (auth.uid() = user_id);
