-- MathComplete Lab authentication, authorization, and idempotent progress migration.
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists email text;
alter table public.profiles add column if not exists display_name text not null default '';
alter table public.profiles add column if not exists created_at timestamptz not null default now();
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

create table if not exists public.account_entitlements (
  user_id uuid primary key references auth.users(id) on delete cascade,
  plan text not null default 'free' check (plan in ('free', 'plus')),
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'profiles' and column_name = 'plan'
  ) then
    insert into public.account_entitlements (user_id, plan)
    select id, case when plan = 'plus' then 'plus' else 'free' end
    from public.profiles
    on conflict (user_id) do nothing;
    alter table public.profiles drop column plan;
  end if;
end $$;

insert into public.account_entitlements (user_id)
select id from auth.users
on conflict (user_id) do nothing;

create table if not exists public.user_consents (
  user_id uuid primary key references auth.users(id) on delete cascade,
  terms_version text not null,
  privacy_version text not null,
  age_confirmed boolean not null check (age_confirmed),
  accepted_at timestamptz not null default now()
);

create table if not exists public.attempts (
  id bigint generated by default as identity primary key,
  client_attempt_id uuid not null default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  game_id text not null,
  course text not null default '',
  topic text not null default '',
  difficulty text not null default '',
  question_key text not null,
  question_latex text not null default '',
  question_text text not null default '',
  correct_answer_latex text not null default '',
  selected_answer_latex text not null default '',
  is_correct boolean not null default false,
  time_spent_seconds integer check (time_spent_seconds is null or time_spent_seconds >= 0),
  created_at timestamptz not null default now(),
  unique (user_id, client_attempt_id)
);

alter table public.attempts add column if not exists client_attempt_id uuid default gen_random_uuid();
update public.attempts set client_attempt_id = gen_random_uuid() where client_attempt_id is null;
alter table public.attempts alter column client_attempt_id set not null;
create unique index if not exists attempts_user_client_attempt_idx on public.attempts (user_id, client_attempt_id);

create table if not exists public.mistakes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  game_id text not null,
  course text not null default '',
  topic text not null default '',
  difficulty text not null default '',
  question_key text not null,
  question_latex text not null default '',
  question_text text not null default '',
  correct_answer_latex text not null default '',
  last_selected_answer_latex text not null default '',
  mistake_count integer not null default 1 check (mistake_count >= 0),
  review_success_count integer not null default 0 check (review_success_count >= 0),
  status text not null default 'active' check (status in ('active', 'mastered')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, game_id, question_key)
);

create table if not exists public.favorite_tools (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  game_id text not null,
  created_at timestamptz not null default now(),
  unique (user_id, game_id)
);

create table if not exists public.mfa_recovery_codes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  code_hash text not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists attempts_user_created_idx on public.attempts (user_id, created_at desc);
create index if not exists mistakes_user_status_updated_idx on public.mistakes (user_id, status, updated_at desc);
create index if not exists favorite_tools_user_created_idx on public.favorite_tools (user_id, created_at desc);
create index if not exists mfa_recovery_codes_user_unused_idx on public.mfa_recovery_codes (user_id, created_at desc) where used_at is null;

create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = public, pg_temp as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles for each row execute function public.set_updated_at();
drop trigger if exists entitlements_set_updated_at on public.account_entitlements;
create trigger entitlements_set_updated_at before update on public.account_entitlements for each row execute function public.set_updated_at();

create or replace function public.handle_auth_user_created()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  accepted timestamptz;
begin
  insert into public.profiles (id, email, display_name)
  values (new.id, new.email, left(coalesce(new.raw_user_meta_data ->> 'display_name', split_part(coalesce(new.email, ''), '@', 1)), 80))
  on conflict (id) do update set email = excluded.email;

  insert into public.account_entitlements (user_id) values (new.id)
  on conflict (user_id) do nothing;

  if coalesce((new.raw_user_meta_data ->> 'age_confirmed')::boolean, false) then
    begin
      accepted := coalesce((new.raw_user_meta_data ->> 'consent_accepted_at')::timestamptz, now());
    exception when others then
      accepted := now();
    end;
    insert into public.user_consents (user_id, terms_version, privacy_version, age_confirmed, accepted_at)
    values (
      new.id,
      left(coalesce(new.raw_user_meta_data ->> 'terms_version', 'unknown'), 40),
      left(coalesce(new.raw_user_meta_data ->> 'privacy_version', 'unknown'), 40),
      true,
      accepted
    )
    on conflict (user_id) do nothing;
  end if;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_auth_user_created();

create or replace function public.handle_auth_user_email_updated()
returns trigger language plpgsql security definer set search_path = public, pg_temp as $$
begin
  update public.profiles set email = new.email where id = new.id;
  return new;
end;
$$;
drop trigger if exists on_auth_user_email_updated on auth.users;
create trigger on_auth_user_email_updated after update of email on auth.users for each row execute function public.handle_auth_user_email_updated();

create or replace function public.mfa_requirement_satisfied()
returns boolean
language sql
stable
security definer
set search_path = public, auth, pg_temp
as $$
  select array[coalesce(auth.jwt() ->> 'aal', 'aal1')] <@ (
    select case when count(id) > 0 then array['aal2'] else array['aal1', 'aal2'] end
    from auth.mfa_factors
    where user_id = auth.uid() and status = 'verified'
  );
$$;

create or replace function public.accept_current_consents(
  p_terms_version text,
  p_privacy_version text,
  p_age_confirmed boolean
)
returns public.user_consents
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare result public.user_consents;
begin
  if auth.uid() is null or p_age_confirmed is not true then raise exception 'consent_required'; end if;
  insert into public.user_consents (user_id, terms_version, privacy_version, age_confirmed, accepted_at)
  values (auth.uid(), left(p_terms_version, 40), left(p_privacy_version, 40), true, now())
  on conflict (user_id) do update set terms_version = excluded.terms_version, privacy_version = excluded.privacy_version, age_confirmed = true, accepted_at = now()
  returning * into result;
  return result;
end;
$$;

create or replace function public.record_attempt(p_attempt jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  uid uuid := auth.uid();
  client_id uuid;
  attempt_row public.attempts;
  mistake_row public.mistakes;
  created_time timestamptz;
begin
  if uid is null then raise exception 'authentication_required'; end if;
  if not public.mfa_requirement_satisfied() then raise exception 'mfa_required'; end if;
  client_id := coalesce(nullif(p_attempt ->> 'client_attempt_id', '')::uuid, gen_random_uuid());
  begin created_time := coalesce(nullif(p_attempt ->> 'created_at', '')::timestamptz, now());
  exception when others then created_time := now(); end;

  insert into public.attempts (
    client_attempt_id, user_id, game_id, course, topic, difficulty, question_key,
    question_latex, question_text, correct_answer_latex, selected_answer_latex,
    is_correct, time_spent_seconds, created_at
  ) values (
    client_id, uid, left(coalesce(p_attempt ->> 'game_id', 'unknown-game'), 120),
    left(coalesce(p_attempt ->> 'course', ''), 120), left(coalesce(p_attempt ->> 'topic', ''), 160),
    left(coalesce(p_attempt ->> 'difficulty', ''), 80), left(coalesce(p_attempt ->> 'question_key', ''), 180),
    left(coalesce(p_attempt ->> 'question_latex', ''), 12000), left(coalesce(p_attempt ->> 'question_text', ''), 12000),
    left(coalesce(p_attempt ->> 'correct_answer_latex', ''), 8000), left(coalesce(p_attempt ->> 'selected_answer_latex', ''), 8000),
    coalesce((p_attempt ->> 'is_correct')::boolean, false),
    greatest(0, nullif(p_attempt ->> 'time_spent_seconds', '')::integer), created_time
  )
  on conflict (user_id, client_attempt_id) do nothing
  returning * into attempt_row;

  if attempt_row.id is null then
    select * into attempt_row from public.attempts where user_id = uid and client_attempt_id = client_id;
    return jsonb_build_object('attempt', to_jsonb(attempt_row), 'mistake', null, 'duplicate', true);
  end if;

  if not attempt_row.is_correct then
    insert into public.mistakes (
      user_id, game_id, course, topic, difficulty, question_key, question_latex,
      question_text, correct_answer_latex, last_selected_answer_latex, mistake_count,
      review_success_count, status, created_at, updated_at
    ) values (
      uid, attempt_row.game_id, attempt_row.course, attempt_row.topic, attempt_row.difficulty,
      attempt_row.question_key, attempt_row.question_latex, attempt_row.question_text,
      attempt_row.correct_answer_latex, attempt_row.selected_answer_latex, 1, 0, 'active', now(), now()
    )
    on conflict (user_id, game_id, question_key) do update set
      course = excluded.course, topic = excluded.topic, difficulty = excluded.difficulty,
      question_latex = excluded.question_latex, question_text = excluded.question_text,
      correct_answer_latex = excluded.correct_answer_latex,
      last_selected_answer_latex = excluded.last_selected_answer_latex,
      mistake_count = public.mistakes.mistake_count + 1,
      review_success_count = 0, status = 'active', updated_at = now()
    returning * into mistake_row;
  end if;
  return jsonb_build_object('attempt', to_jsonb(attempt_row), 'mistake', to_jsonb(mistake_row));
end;
$$;

alter table public.profiles enable row level security;
alter table public.account_entitlements enable row level security;
alter table public.user_consents enable row level security;
alter table public.attempts enable row level security;
alter table public.mistakes enable row level security;
alter table public.favorite_tools enable row level security;
alter table public.mfa_recovery_codes enable row level security;

drop policy if exists profiles_select_own on public.profiles;
drop policy if exists profiles_insert_own on public.profiles;
drop policy if exists profiles_update_own on public.profiles;
create policy profiles_select_own on public.profiles for select to authenticated using (auth.uid() = id);
create policy profiles_update_own on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists entitlements_select_own on public.account_entitlements;
create policy entitlements_select_own on public.account_entitlements for select to authenticated using (auth.uid() = user_id);
drop policy if exists consents_select_own on public.user_consents;
create policy consents_select_own on public.user_consents for select to authenticated using (auth.uid() = user_id);

drop policy if exists attempts_select_own on public.attempts;
drop policy if exists attempts_insert_own on public.attempts;
create policy attempts_select_own on public.attempts for select to authenticated using (auth.uid() = user_id);

drop policy if exists mistakes_select_own on public.mistakes;
drop policy if exists mistakes_insert_own on public.mistakes;
drop policy if exists mistakes_update_own on public.mistakes;
create policy mistakes_select_own on public.mistakes for select to authenticated using (auth.uid() = user_id);
create policy mistakes_update_own on public.mistakes for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists favorite_tools_select_own on public.favorite_tools;
drop policy if exists favorite_tools_insert_own on public.favorite_tools;
drop policy if exists favorite_tools_delete_own on public.favorite_tools;
create policy favorite_tools_select_own on public.favorite_tools for select to authenticated using (auth.uid() = user_id);
create policy favorite_tools_insert_own on public.favorite_tools for insert to authenticated with check (auth.uid() = user_id);
create policy favorite_tools_delete_own on public.favorite_tools for delete to authenticated using (auth.uid() = user_id);

do $$
declare table_name text;
begin
  foreach table_name in array array['profiles','account_entitlements','user_consents','attempts','mistakes','favorite_tools'] loop
    execute format('drop policy if exists %I on public.%I', table_name || '_mfa_access', table_name);
    execute format('create policy %I on public.%I as restrictive for all to authenticated using (public.mfa_requirement_satisfied()) with check (public.mfa_requirement_satisfied())', table_name || '_mfa_access', table_name);
  end loop;
end $$;

revoke all on public.account_entitlements from anon, authenticated;
grant select on public.account_entitlements to authenticated;
revoke all on public.user_consents from anon, authenticated;
grant select on public.user_consents to authenticated;
revoke all on public.mfa_recovery_codes from anon, authenticated;
revoke insert, delete on public.profiles from authenticated;
revoke update on public.profiles from authenticated;
grant select on public.profiles to authenticated;
grant update (display_name) on public.profiles to authenticated;
grant select on public.attempts, public.mistakes, public.favorite_tools to authenticated;
grant update (status) on public.mistakes to authenticated;
grant insert, delete on public.favorite_tools to authenticated;
grant execute on function public.record_attempt(jsonb) to authenticated;
grant execute on function public.accept_current_consents(text, text, boolean) to authenticated;
revoke all on function public.mfa_requirement_satisfied() from public;
grant execute on function public.mfa_requirement_satisfied() to authenticated;
